---
abstract: 'Class for communication with backend by sending messaging through redis streams.'
author:
  - 'DERIV <DERIV@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::MockObject: '0'
  Test::More: '0.98'
  Test::NoTabs: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '7.64'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-WebSocketProxy-Backend-ConsumerGroups
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Mojo::WebSocketProxy::Backend::ConsumerGroups:
    file: lib/Mojo/WebSocketProxy/Backend/ConsumerGroups.pm
    version: '0.02'
requires:
  Data::UUID: '0'
  IO::Async::Loop::Mojo: '0'
  JSON::MaybeUTF8: '0'
  Log::Any: '0'
  Mojo::Redis2: '0'
  Mojo::WebSocketProxy: '0.13'
  Mojo::WebSocketProxy::Backend: '0'
  MojoX::JSON::RPC::Client: '0'
  Syntax::Keyword::Try: '0'
  constant: '0'
  curry::weak: '0'
  indirect: '0.37'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/mariovw-deriv/perl-Mojo-WebSocketProxy-Backend-ConsumerGroups/issues
  homepage: https://github.com/mariovw-deriv/perl-Mojo-WebSocketProxy-Backend-ConsumerGroups
  repository: https://github.com/mariovw-deriv/perl-Mojo-WebSocketProxy-Backend-ConsumerGroups.git
version: '0.02'
x_authority: cpan:DERIV
x_contributors:
  - 'user <user@binary.com>'
  - 'chylli-binary <52912308+chylli-binary@users.noreply.github.com>'
  - 'Raunak Kathuria <raunakkathuria@gmail.com>'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
